function onClickSenha(){
	document.getElementById("pagnone").innerHTML ="<div class='text-center text-light w-100'><form method='POST' action='alterar_senha.php' class='d-inline-block m-5 gradient-secondary destaque-radius-shadow' name='f1'><div class='form-row text-center'><div class='form-group col-sm-12 w-100 pt-5 pb-4 px-5'><label for='inputSenha'>Digite sua senha anterior: <h11>*</h11></label><input type='password' name='pwd' id='inputSenha' maxlength='12' minlength='8' required title='Tem que ter no mínimo 8 letras e no máximo 12 tendo no mínimo uma letra minuscula de [a-z]' requireds class='form-control shadow-lg'><br><label for='inputSenha'>Digite a nova senha <h11>*</h11></label><input type='password' name='pwd1' id='inputSenha' maxlength='12' minlength='8' required onchange='form.pwd2.pattern = this.value;' title='Não pode ser igual a antiga, tendo no mínimo 8 letras e no máximo 12 devendo ter uma letra de [a-z]' required  class='form-control shadow-lg'><br><label for='inputSenha2'>Confirmar nova senha: <h11>*</h11></label><input type='password' name='pwd2'  id='inputSenha2' maxlength='12' minlength='8' title='As Senhas Devem ser Iguais' required9- class='form-control shadow-lg'></div></div><div class='form-row px-5 pb-5'><div class='form-group m-auto w-100'><input type='submit' value='Enviar' id='' class='w-100 btn btn-success'></div></div></form></div>";

}

function onClickDados(){
	document.getElementById("pagnone").innerHTML ='';
}

function onClickPlantacao() {
	document.getElementById("pagnone").innerHTML='Ola';
}

function onClickCronograma() {
	document.getElementById("pagnone").innerHTML='<div class=""><div class="text-center w-100"><form method="POST" action="" class="d-inline-block" name="f1"><div class="form-row text-center"><div class="form-group col-sm-12 d-inline"><label>Digite o <label class="font-weight-bold">horário</label> de inicio <label class="font-weight-bold">diário</label> ("utilize o formato 24 horas") <h11>*</h11></label><br><label for="inputHora" class="w-25">horas<input type="number" name="horas" onkeypress="verificar1();" id="inputHorasI" min="0" max="24" required class="form-control"></label><label class="font-weight-bold" style="font-size: 1.6em">:</label><label for="inputMinutos"  class="w-25">minutos <h11>*</h11><input type="number" onkeypress="verificar2();" name="minutos" id="inputMinutosI" min="0" max="59" required class="form-control"></label><br><br><label>Digite o <label class="font-weight-bold">horário</label> de termino <label class="font-weight-bold">diário</label> ("utilize o formato 24 horas") <h11>*</h11></label><br><label for="inputHora" class="w-25">horas<input type="number" min="0" max="24" name="horas" id="inputHorasT" maxlength="2" required class="form-control"></label><label class="font-weight-bold" style="font-size: 1.6em">:</label><label for="inputMinutos" class="w-25">minutos <h11>*</h11><input type="number" min="0" max="59" name="minutos" id="inputMinutosT" maxlength="2" required class="form-control"></label><br><br></div></div><div class="form-row text-center"><div class="form-group col-sm-12 d-inline"><label for="inputDias">Dias de Execução</label> <h11>*</h11><select name="dias"  id="inputDias" onchange="diasvalor(this.value);" required class="form-control w-75 mx-auto"><option value="0">Definir cronograma como pradrão</option><option value="1">Executar cronograma só uma vez</option><option value="2">Definir manualmente o cronograma:</option></select></div></div><br><br><div id="divDias"></div><br><br><div class="form-row text-center"><div class="form-group col-sm-12 d-inline"><label for="">Numero do Plantio: ("Este Numero é dado na área do <label class="font-weight-bold">Cronograma RTOS</label>") <h11>*</h11></label><input type="number" name=""  id="" maxlength="15" required class="form-control w-50 mx-auto"></div></div><br><br><div class="form-row"><div class="form-group col-sm-12"><input type="submit" value="Enviar" id="" class="w-100 btn btn-success"></div></div></form></div></div>';
}

function onClickCadastro_Modulo() {
	document.getElementById("pagnone").innerHTML='<div class="text-center text-light w-100"><form method="POST" action="loginMod.php" class="d-inline-block m-5 gradient-secondary destaque-radius-shadow" name="f1"><div class="form-row text-center"><div class="form-group col-sm-12 w-100 pt-5 pb-4 px-5"><label for="Mod_nome">Digite seu Nome de Moderador <h11>*</h11></label><input type="text" name="Mod_nome" id="inputMod_nome" maxlength="20" required class="form-control shadow-lg"><br><label for="Mod_senha">Digite sua senha <h11>*</h11></label><input type="password" name="Mod_senha" id="inputMod_senha" maxlength="20"  required  class="form-control shadow-lg"></div></div><div class="form-row px-5 pb-5"><div class="form-group m-auto w-100"><input type="submit" value="Enviar" id="" class="w-100 btn btn-success"></div></div></form></div>';
}

